### PR TITLE
add nested fields support

### PR DESCRIPTION
**Pull request by jakepusateri**
Related to #2

### CODE REVIEW

**Comment by jakepusateri** [comment]
To answer before merge:
1. Is this breaking? `{ a { b } }`  would have returned `['a']` but now returns `['a.b']`.
2. Should that example actually return `['a', 'a.b']`?

**Comment by rblalock** [comment]
This going to be merged anytime?

**Comment by aryzle** [comment]
👍

**Comment by lmachens** [comment]
Looks fine for me, can you merge it?

**Comment by Zakjholt** [comment]
Plzzzz

**Comment by jakepusateri** [comment]
Published in @2.0.0

**Comment by dandv** [comment]
Can you please add some documentation in the README about how to use nested fields? Right now, when finding the module on NPM, the API looks very barebones, without nested field support.

**Pull request merged**
